### ISSUE TITLE
Problem with mouse stuck in drag mode if user moves mouse past left side of window.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_Viewer#1]
Open a map in viewer.
Click and drag mouse on divider bar.
Continue moving mouse left past edge of map container and release mouse button.
Move mouse back over map.  
Divider bar will keep moving with it even though mouse button not pressed (i.e. not in drag mode)
Can only seem to escape by double-clicking in map somewhere.

**Comment by jmelott** [comment]
Issue still exists 4/2/2020

**Comment by jma7** [comment]
It seems this is a problem with the NGCHM within iframe. The embedded NGCHM has the same behavior.

**Comment by ChrisWakefield** [comment]
Confirmed this is a problem in the viewer, and that it is being fixed there.  Close this for now.
