### ISSUE TITLE
Detailed view of maps will often turn white and hang a while when switching between full and partial map.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_Viewer#2]
Make a 2000x2000 map with the data matrix in the attached zip file.
View the map and try zooming out quickly until it displays the whole map.
The detail map will often turn white and the software will be unresponsive when switching between full and partial map views.
[matrix_11_2000_2000_samples_samples.zip](https://github.com/MD-Anderson-Bioinformatics/GenePattern_NGCHM_Viewer/files/4299855/matrix_11_2000_2000_samples_samples.zip)

**Comment by jmelott** [comment]
Still flashing white, but doesn't seem to hang like before.  Possibly due to running on a different server?

**Comment by jmelott** [comment]
Slight hang up with larger maps like 3200 x 3200

**Comment by ChrisWakefield** [comment]
@jmelott @jma7 This sounds similar to what Mark was showing in last week's meeting.  In particular, he was showing that typing in the search bar caused it to redraw between each keystroke, and that became very slow.  We need to verify this is or is not an expected behavior, i.e. the viewer already does this outside of GenePattern Notebook.

**Comment by jmelott** [comment]
This isn't related to the search feature.
It does exist in the normal viewer somewhat, but seems much worse in the GenePattern viewer for some reason.  It seems to come up on the GenePattern viewer for much smaller maps and so far I haven't seen it freeze the page in the stand alone viewer like it seems to do sometimes in the GenePattern one.

**Comment by jma7** [comment]
This is a NG-CHM issue. I don't observe this issues is better or worse in GenePattern though.

**Comment by jmelott** [comment]
GenePattern viewer and Standalone viewer seem to be behaving similarly for large maps now and neither is freezing the response the way I saw before.

**Comment by ChrisWakefield** [comment]
We should ask Mark to comment on if there was a change.

**Comment by jmelott** [comment]
It could be that switching the builder and/or viewer to the latest version fixed something or it could be that I was testing in embedded Python Notebooks before and/or going through VX remote while testing was causing extra delays.  Currently I'm using the VPN instead of VX Remote and testing in GenePattern instead of within a GenePattern notebook.
