### ISSUE TITLE
Download standalone viewer from within heat map returns 404 error

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_Viewer#4]
Tested on udev6.  
Steps to reproduce:
Open map in viewer.
Try to download heat map.  (fails to download ngchm file, but asks then if you want to download the standalone viewer).
Click "Download Viewer" button.
Heat map replaced with page displaying "404 Not Found".

**Comment by jma7** [comment]
This looks like a bug in the NG-CHM, just tried in the panel view viewer which has the same problem

**Comment by ChrisWakefield** [comment]
This was a problem in setup at ngchm.net.  Fixed now.  We need to retest.

**Comment by jma7** [comment]
This problem has been fixed by Dr.Broom.
